#############################################################################
# Makefile for building: knightsTourProjectCode
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Nov 17 14:49:05 2011
# Project:  knightsTourProjectCode.pro
# Template: app
# Command: /usr/bin/qmake -config release -o Makefile knightsTourProjectCode.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = emitter.cpp \
		glEngine.cpp \
		GLWidget.cpp \
		light.cpp \
		main.cpp \
		mainwindow.cpp \
		model.cpp \
		particle.cpp \
		texture.cpp moc_GLWidget.cpp \
		moc_mainwindow.cpp
OBJECTS       = emitter.o \
		glEngine.o \
		GLWidget.o \
		light.o \
		main.o \
		mainwindow.o \
		model.o \
		particle.o \
		texture.o \
		moc_GLWidget.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		knightsTourProjectCode.pro
QMAKE_TARGET  = knightsTourProjectCode
DESTDIR       = 
TARGET        = knightsTourProjectCode

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: knightsTourProjectCode.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -config release -o Makefile knightsTourProjectCode.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -config release -o Makefile knightsTourProjectCode.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/knightsTourProjectCode1.0.0 || $(MKDIR) .tmp/knightsTourProjectCode1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/knightsTourProjectCode1.0.0/ && $(COPY_FILE) --parents emitter.h glEngine.h GLWidget.h light.h mainwindow.h model.h particle.h texture.h ui_mainwindow.h vector3.h .tmp/knightsTourProjectCode1.0.0/ && $(COPY_FILE) --parents emitter.cpp glEngine.cpp GLWidget.cpp light.cpp main.cpp mainwindow.cpp model.cpp particle.cpp texture.cpp .tmp/knightsTourProjectCode1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/knightsTourProjectCode1.0.0/ && (cd `dirname .tmp/knightsTourProjectCode1.0.0` && $(TAR) knightsTourProjectCode1.0.0.tar knightsTourProjectCode1.0.0 && $(COMPRESS) knightsTourProjectCode1.0.0.tar) && $(MOVE) `dirname .tmp/knightsTourProjectCode1.0.0`/knightsTourProjectCode1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/knightsTourProjectCode1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GLWidget.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GLWidget.cpp moc_mainwindow.cpp
moc_GLWidget.cpp: model.h \
		vector3.h \
		GLWidget.h \
		emitter.h \
		particle.h \
		texture.h \
		light.h \
		GLWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GLWidget.h -o moc_GLWidget.cpp

moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

emitter.o: emitter.cpp emitter.h \
		particle.h \
		vector3.h \
		GLWidget.h \
		model.h \
		texture.h \
		light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emitter.o emitter.cpp

glEngine.o: glEngine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glEngine.o glEngine.cpp

GLWidget.o: GLWidget.cpp GLWidget.h \
		model.h \
		vector3.h \
		texture.h \
		emitter.h \
		particle.h \
		light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLWidget.o GLWidget.cpp

light.o: light.cpp light.h \
		GLWidget.h \
		model.h \
		vector3.h \
		texture.h \
		emitter.h \
		particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

main.o: main.cpp GLWidget.h \
		model.h \
		vector3.h \
		texture.h \
		emitter.h \
		particle.h \
		light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

model.o: model.cpp model.h \
		vector3.h \
		GLWidget.h \
		emitter.h \
		particle.h \
		texture.h \
		light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cpp

particle.o: particle.cpp particle.h \
		vector3.h \
		GLWidget.h \
		model.h \
		texture.h \
		emitter.h \
		light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o particle.o particle.cpp

texture.o: texture.cpp texture.h \
		GLWidget.h \
		model.h \
		vector3.h \
		emitter.h \
		particle.h \
		light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texture.o texture.cpp

moc_GLWidget.o: moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLWidget.o moc_GLWidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

